poll/urls.py
from django.conf.urls import patterns, url

from poll.views import charts, views, admin

# USER = '(?P<username>([0-9]|[a-z]|[A-Z])+)'

urlpatterns = [
    url(r'^questionnaire/$', views.QuestionnaireView.as_view(), name='questionnaire'),
    url(r'^update_polldate_score/$', views.UpdatePollDateScore.as_view(), name='update_polldate_score'),
    url(r'^score/$', charts.ScoreView.as_view(), name='score'),
    url(r'^graphic/$', charts.GBarView.as_view(), name='graphic'),
    url(r'^practice_score_column_chart/$', charts.PracticeScoreColumnChart.as_view(), name='practice_score_column_chart'),
    url(r'^question_line_chart/$', charts.QuestionLineChart.as_view(), name='question_line_chart'),
    url(r'^poll_date_bar_chart/$', charts.PollDateBarChart.as_view(), name='poll_date_bar_chart'),
    url(r'^poll_date_line_chart/$', charts.PollDateLineChart.as_view(), name='poll_date_line_chart'),
    url(r'^question_bar_chart/$', charts.QuestionBarChart.as_view(), name='question_bar_chart'),
    url(r'^poll_list/$', views.PollListView.as_view(), name='poll_list'),

    url(r'^demographics/$', views.DemographicsFormView.as_view(), name='demographics'),

    # admin json views
    url(r'^answers_by_user_json_view/$', admin.AnswersByUserJsonView.as_view(), name='answers_by_user_json_view'),
    url(r'^questionnaire/(?P<poll>[-\w]+)/$', views.QuestionnaireView.as_view(), name='questionnaire'),
]

siaiepi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout, password_change, password_change_done


# my urls
from django.views.generic.base import TemplateView

from poll.views import views
from siaiepi.views import login

urlpatterns = [
    url(r'^$', views.DemographicsFormView.as_view(), name='home'),
    url(r'^poll/', include('poll.urls', namespace='poll', app_name='poll')),
]

# django urls
urlpatterns += [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, {'template_name': 'pages/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url('^password_change/', password_change, {'template_name': 'registration/password_change.html'},
        name='password_change'),
    url('^password_change_done/', password_change_done, {'template_name': 'pages/password_change_done.html'},
        name='password_change_done'),
]

# fiber url
# urlpatterns += [
#     url(r'^admin/fiber/', include('fiber.admin_urls')),
#     url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('fiber',),}),
#     url(r'^api/v2/', include('fiber.rest_api.urls')),
#     url(r'', 'fiber.views.page'),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modern_business/templates/include/menu.html
{% load solo_tags i18n poll_tag thumbnail %}
{% get_solo 'config.SIIMCIConfig' as config %}
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'home' %}">
                {% if config.logo %}
                    <img src='{% thumbnail config.logo 0x30 %}'/>
                {% else %}
                    {{ config.site_name }}
                {% endif %}
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {#{% show_menu "mainmenu" 1 5 "all" %}#}
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    {% if perms.poll.is_respondent and user.respondent %}
                        <li>
                            <a href="{% url 'poll:questionnaire' %}">{% trans 'Questionnaire' %}</a>
                        </li>
                        <li>
                            <a href="{% url 'poll:graphic' %}">{% trans 'Graphic' %}</a>
                        </li> <li>
                            <a href="{% url 'poll:demographics' %}">{% trans 'Demographics data' %}</a>
                        </li>
                    {% endif %}
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ user.username }}
                            <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="{% url 'password_change' %}">{% trans 'Change password' %}</a>
                            </li>
                            <li>
                                <a href="{% url 'logout' %}">{% trans 'Logout' %}</a>
                            </li>
                        </ul>
                    </li>
                {% else %}
                    <li>
                        <a href="{% url 'login' %}">{% trans 'Login' %}</a>
                    </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>