poll/urls.py
from django.conf.urls import patterns, url

from poll.views import charts, views, admin

# USER = '(?P<username>([0-9]|[a-z]|[A-Z])+)'

urlpatterns = [
    url(r'^questionnaire/$', views.QuestionnaireView.as_view(), name='questionnaire'),
    url(r'^update_polldate_score/$', views.UpdatePollDateScore.as_view(), name='update_polldate_score'),
    url(r'^score/$', charts.ScoreView.as_view(), name='score'),
    url(r'^graphic/$', charts.GBarView.as_view(), name='graphic'),
    url(r'^practice_score_column_chart/$', charts.PracticeScoreColumnChart.as_view(), name='practice_score_column_chart'),
    url(r'^question_line_chart/$', charts.QuestionLineChart.as_view(), name='question_line_chart'),
    url(r'^poll_date_bar_chart/$', charts.PollDateBarChart.as_view(), name='poll_date_bar_chart'),
    url(r'^poll_date_line_chart/$', charts.PollDateLineChart.as_view(), name='poll_date_line_chart'),
    url(r'^question_bar_chart/$', charts.QuestionBarChart.as_view(), name='question_bar_chart'),
    url(r'^poll_list/$', views.PollListView.as_view(), name='poll_list'),

    url(r'^demographics/$', views.DemographicsFormView.as_view(), name='demographics'),

    # admin json views
    url(r'^answers_by_user_json_view/$', admin.AnswersByUserJsonView.as_view(), name='answers_by_user_json_view'),
    url(r'^questionnaire/(?P<poll>[-\w]+)/$', views.QuestionnaireView.as_view(), name='questionnaire'),
]

siaiepi/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import logout, password_change, password_change_done


# my urls
from django.views.generic.base import TemplateView

from poll.views import views
from siaiepi.views import login

urlpatterns = [
    url(r'^$', views.DemographicsFormView.as_view(), name='home'),
    url(r'^poll/', include('poll.urls', namespace='poll', app_name='poll')),
]

# django urls
urlpatterns += [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', login, {'template_name': 'pages/login.html'}, name='login'),
    url(r'^logout/$', logout, {'next_page': '/'}, name='logout'),
    url('^password_change/', password_change, {'template_name': 'registration/password_change.html'},
        name='password_change'),
    url('^password_change_done/', password_change_done, {'template_name': 'pages/password_change_done.html'},
        name='password_change_done'),
]

# fiber url
# urlpatterns += [
#     url(r'^admin/fiber/', include('fiber.admin_urls')),
#     url(r'^jsi18n/$', 'django.views.i18n.javascript_catalog', {'packages': ('fiber',),}),
#     url(r'^api/v2/', include('fiber.rest_api.urls')),
#     url(r'', 'fiber.views.page'),
# ]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

modern_business/templates/highcharts/graphic.html
{% extends "base.html" %}
{% load staticfiles i18n modern_tags %}
{% block breadcrumb %}
    <li><a href="{% url 'home' %}">{% trans 'Home' %}</a></li>
    <li class="active">{% trans 'Graphics' %}</li>
{% endblock %}
{% block page_header %}
    {% trans 'Graphics' %}
{% endblock %}
{% block main %}
    <div id="column_chart" data-url="{% url 'poll:practice_score_column_chart' %}" data-username="{{ request.user.username }}"></div>
    <div>
        <table class="table table-hover">
            <thead>
            <tr>
                <th>{% trans 'Practice' %}</th>
                {% for c in categories_p %}
                    <th>{{ c }}</th>
                {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for r in result_p %}
                <tr>
                    <td>{{ r.name }}</td>
                    {% for d in r.data %}
                        <td>{{ d }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
    <div id="line_chart" data-url="{% url 'poll:question_line_chart' %}"  data-username="{{ request.user.username }}"></div>
    <div>
        <table class="table table-hover">
            <thead>
            <!--<tr>-->
            <th>{% trans 'Questions' %}</th>
            {% for c in categories_q %}
                <th>{{ c }}</th>
            {% endfor %}
            </tr>
            </thead>
            <tbody>
            {% for r in result_q %}
                <tr>
                    <td>{{ r.name }}</td>
                    {% for data in r.datas %}
                        <td class="tooltip-td-{{ data.answer.type }}">
                            <span class="tooltip-{{ data.answer.type }}">
                                {{ data.data }} - {{ data.text }}
                            </span>
                            <div class="hidden tooltip-hide">
                                {% if data.answer.type == 'options' %}
                                    {% for option in data.answer.options.all %}
                                        <li>{{ option }}</li>
                                    {% endfor %}
                                {% endif %}
                            </div>
                        </td>
                    {% endfor %}
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}
{% block extrajs %}
    <script src="{% static 'js/highcharts/highcharts.js' %}"></script>
    <script src="{% static 'js/highcharts/exporting.js' %}"></script>
    <script src="{% static 'js/poll/tools.js' %}"></script>
{% endblock %}